---
namespace: amarao

name: ip

version: 0.1.4

readme: README.md

authors:
  - George Shuklin <george.shuklin@gmail.com>
  - Ivan Semenov <ivan@semenov.dev>

description: Collection of wrappers for iproute2 utility (/bin/ip) for managing network devices, addreses and routes.

license:
  - GPL-3.0-or-later

tags: [ip, linux]

dependencies: {}

repository: https://github.com/amarao/collection_ip

documentation: https://github.com/amarao/collection_ip/README.md

homepage: https://github.com/amarao/collection_ip

issues: https://github.com/amarao/collection_ip/issues
