# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sanity tests with dependencies
      run: ansible-test sanity --requirements --python 3.8
      working-directory: ansible_collections/amarao/ip
    - name: Unit tests with dependencies
      run: ansible-test units --requirements --python 3.8
      working-directory: ansible_collections/amarao/ip
    - name: Integration tests
      run: ansible-test integration --requirements --python 3.8 --local --allow-root
      working-directory: ansible_collections/amarao/ip
    - name: Cleanup
      run: rm -r ansible_collections/amarao/ip/tests/output
